table 'Inspector Dim'
	lineageTag: 109ba03d-6228-469e-9c84-4a79845e93f9

	column 'Inspector ID'
		dataType: string
		lineageTag: 51e1dc8a-3640-4484-b94d-b641af96b2f4
		summarizeBy: none
		sourceColumn: Inspector ID

		annotation SummarizationSetBy = Automatic

	column 'Inspector Name'
		dataType: string
		lineageTag: 8f50198a-c410-4aff-9f5b-7db480fb3ed6
		summarizeBy: none
		sourceColumn: Inspector Name

		annotation SummarizationSetBy = Automatic

	column 'Certification Level'
		dataType: string
		lineageTag: ab242789-6ed6-435a-9fa4-b24d131efe68
		summarizeBy: none
		sourceColumn: Certification Level

		annotation SummarizationSetBy = Automatic

	partition 'Inspector Dim' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("PdBPa8JAEAXwrzLkLJLU/j1arS3RgJhCD5LD1Izu4G4GZhOFfvqm7Wyv8+MNj7ffZ3leZJNsqVOoUBlhJ63yaaCvrJn86I1piYEiLBx1BrMRtirHKdSo6KAU10VJemuxnXyS9rDmYHBnsOGI8IHdye73dl/ihVuoA/fO5MFkhT0HhLkL1Bo9Gr07CRjhWeWaCjwZvXjqELbUq1zwz4rcbIHqJULN/p/SGPNuTK3lij6e2SxNUfHBIXnYEJnMTGo5jhO+oh44PUxD/NaGN4wRrWKRpigHP6aqwXvSrGm+AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Inspector ID" = _t, #"Inspector Name" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Inspector ID", Int64.Type}, {"Inspector Name", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Inspector ID", "Inspecto_ ID"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Inspector ID", each Text.PadStart(Text.From([Inspecto_ ID]),3,"0")),
				    #"Removed Columns" = Table.AddColumn(#"Added Custom", "Certification Level", each if [Inspector ID] = "001" then "Level 1" else if [Inspector ID] = "013" then "Level 1" else if [Inspector ID] = "007" then "Level 1" else if [Inspector ID] = "012" then "Level 2" else if [Inspector ID] = "014" then "Level 2" else if [Inspector ID] = "005" then "Level 1" else if [Inspector ID] = "009" then "Level 2" else if [Inspector ID] = "008" then "Level 2" else "Level 3"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Columns",{"Inspecto_ ID"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns1",{"Inspector ID", "Inspector Name", "Certification Level"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns","Prof. Sarah Johnson","Prof.phoebe Buffay",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Dr. David Smith","Dr.Ross Geller",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Dr. Sofia Garcia","Dr. Rachel Green",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Prof.phoebe Buffay","Prof. phoebe Buffay",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Dr.Ross Geller","Dr. Ross Geller",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Dr. Anna Kowalski","Dr. Drake Ramory",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Dr. Thomas Brown","Dr. Chandler Bing",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Dr. Lisa Wang","Dr. Monica Geller",Replacer.ReplaceText,{"Inspector Name"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Dr. Elena Petrova","Dr. Catherina Petrova",Replacer.ReplaceText,{"Inspector Name"})
				in
				    #"Replaced Value8"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

