table Inspections
	lineageTag: 459419d7-a972-4466-87dd-f01881b5d001

	measure 'Total Inspections' = COUNTROWS(Inspections)
		formatString: 0
		lineageTag: b9f2bc08-f0ce-4833-984c-bab81ef8c76f

	measure 'On-Time Rate' = VAR OnTimeCount=CALCULATE([Total Inspections], Inspections[On Time]="On Time")RETURN DIVIDE(OnTimeCount,[Total Inspections])
		lineageTag: 69cba5dd-4df2-409c-9625-563b07a6d662

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Compliance Rate' = VAR ComplilantCount = CALCULATE([Total Inspections],Inspections[Compliance Status]="Compliant") RETURN DIVIDE(ComplilantCount , [Total Inspections])
		lineageTag: dba3a0af-fc79-4fbf-bf32-83b6f50b41fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Inspection Duration' = AVERAGE(Inspections[ Inspection Duration])
		lineageTag: 583a3d4c-75b9-41db-9d5d-86d894c04ba4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inspection Last Month' = CALCULATE([Total Inspections],PREVIOUSMONTH('Calendar'[Date]))
		formatString: 0
		lineageTag: 911c7737-f641-48f5-a264-e68db382ddab

	measure 'MoM Growth' = VAR CurrentMonth =[Total Inspections] VAR PrevMonth=[Inspection Last Month] RETURN DIVIDE(CurrentMonth-PrevMonth , PrevMonth)
		lineageTag: 9fbeda37-ae67-4ab2-9503-8f9dd0dcefd3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inpection MTD' = TOTALMTD([Total Inspections],'Calendar'[Date])
		formatString: 0
		lineageTag: d36f2a5d-2657-4081-a246-32edd4f405d1

	column 'Laboratory Name'
		dataType: string
		lineageTag: 1de83cf3-c05c-42df-b601-545d99a79ffe
		summarizeBy: none
		sourceColumn: Laboratory Name

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: be95fd41-fec6-43ed-952e-66b91fb70d03
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6d7ba1d2-fcf2-4454-8508-2baecf455e22
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Zip
		dataType: string
		lineageTag: 1edcea60-89ce-4057-8886-f515e5119ca8
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column Country/Area
		dataType: string
		lineageTag: ab5077a7-eac8-49da-a9f7-a51472d27c6f
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country/Area

		annotation SummarizationSetBy = Automatic

	column 'Inspection ID'
		dataType: int64
		formatString: 0
		lineageTag: ec0a329f-ea79-4d5b-9fe0-0f21a2e3ef24
		summarizeBy: count
		sourceColumn: Inspection ID

		annotation SummarizationSetBy = Automatic

	column 'Completion Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9069226c-0d3a-4d1a-856e-d033e1ad64f8
		summarizeBy: none
		sourceColumn: Completion Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Compliance Status'
		dataType: string
		lineageTag: 8dadd59b-23ae-4626-aadb-0a6004279fa3
		summarizeBy: none
		sourceColumn: Compliance Status

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 858b4b01-5864-4585-9dc6-be0e20126ad1
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column 'Test Category'
		dataType: string
		lineageTag: be89be90-c07d-418a-ae45-7b6f3198e7b5
		summarizeBy: none
		sourceColumn: Test Category

		annotation SummarizationSetBy = Automatic

	column 'Scheduled Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ec22ee83-2e57-4e30-b580-412855a1343b
		summarizeBy: none
		sourceColumn: Scheduled Date

		variation Variation
			isDefault
			relationship: 13aaa4f1-0e3d-4c53-89d9-ba3c9b71cbd3
			defaultHierarchy: LocalDateTable_cdda724d-cdac-4df7-b5ad-b83d085ad5d9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ' Inspection Duration'
		dataType: int64
		formatString: 0
		lineageTag: f8d34c0c-6f7f-4dc0-bce8-063193669ecb
		summarizeBy: sum
		sourceColumn: " Inspection Duration"

		annotation SummarizationSetBy = Automatic

	column 'On Time'
		dataType: string
		lineageTag: 09f2e1c3-6296-4dfb-b0b6-29927f8ff189
		summarizeBy: none
		sourceColumn: On Time

		annotation SummarizationSetBy = Automatic

	column 'Priority Level'
		dataType: string
		lineageTag: 0323d2e4-a1e9-47e0-8f80-c1a7e98d0254
		summarizeBy: none
		sourceColumn: Priority Level

		annotation SummarizationSetBy = Automatic

	column 'Inspector ID'
		dataType: string
		lineageTag: 9bf99911-7005-4bf7-83e0-f4b933fb0e00
		summarizeBy: none
		sourceColumn: Inspector ID

		annotation SummarizationSetBy = Automatic

	column 'Client ID'
		dataType: string
		lineageTag: e5f6ce12-4bf3-4bb7-9a05-35ab468b9e1e
		summarizeBy: none
		sourceColumn: Client ID

		annotation SummarizationSetBy = Automatic

	partition Inspections = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\chebb\OneDrive\Desktop\Power BI\FDA Inspections.csv"),[Delimiter=",", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"index", Int64.Type}, {"FEI Number", Int64.Type}, {"Legal Name", type text}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"Country/Area", type text}, {"Fiscal Year", Int64.Type}, {"Inspection ID", Int64.Type}, {"Posted Citations", type text}, {"Inspection End Date", type date}, {"Classification", type text}, {"Project Area", type text}, {"Product Type", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Product Type", "Test Category"}, {"Inspection End Date", "Completion Date"}, {"Classification", "ompliance Status"}, {"Legal Name", "Laboratory Name"}, {"Project Area", "Department"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Scheduled_Date", each Date.AddDays([Completion Date],-Number.RoundDown(Number.RandomBetween(-10,15)))),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", " Inspection Duration", each Duration.Days([Completion Date]-[Scheduled_Date])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom1",{{"Scheduled_Date", "Scheduled Date"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Scheduled Date", type date}, {" Inspection Duration", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "On Time", each if [#" Inspection Duration"] <= 0 then "On Time" else if [#" Inspection Duration"] <= 5 then "Slightly Late" else " Very Late"),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Priority Level", each if [Test Category] = "Drug" then "High" else if [Test Category] = "Food/Cosmetics" then "Medium" else if [Test Category] = "Biologics" then "High" else "Low"),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column1",{"FEI Number", "index", "Fiscal Year", "Posted Citations"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"ompliance Status", "Compliance Status"}}),
				    #"Added Custom2" = Table.AddColumn(#"Renamed Columns2", "Inspector ID", each Text.PadStart(
				    Text.From(
				        Number.Mod([Inspection ID], 15) + 1  // Creates numbers 1-15
				    ), 
				    3,  // Pads to 3 digits: 001, 002, etc.
				    "0"
				)),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Client ID", each "C"& Text.PadStart(Text.From(Number.Mod([Inspection ID],20)+1),3,"0")),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom3","No Action Indicated (NAI)","Compliant",Replacer.ReplaceText,{"Compliance Status"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Voluntary Action Indicated (VAI)","Conditional",Replacer.ReplaceText,{"Compliance Status"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Official Action Indicated (OAI)","Non-Compliant",Replacer.ReplaceText,{"Compliance Status"})
				in
				    #"Replaced Value2"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

